title: Metanorma
description: The standard for standards
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

tagline: >-
  We have made<br>the standards of standards tool

pitch: >-
  Because standards documents are too important to manage in Word.

author: "Ribose Inc."

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/riboseinc

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/specs/draft-ribose-asciirfc/", title: "Get Started" }
  - { url: "/samples/", title: "Samples" }

permalink: /blog/:month-:day-:year/:title/
