title: Metanorma
description: The standard for standards
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

author: "Ribose Inc."
tagline: >-
  We have made<br>the standards of standards tool

pitch: >-
  Write open hub pitch here.
  <br>
  It will appear on home page hero unit.


authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

get_started_url: /specs/draft-ribose-asciirfc/

permalink: /blog/:month-:day-:year/:title/
